// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MGData.proto

package com.learning.compress.proto;

public final class MGDataProto {
  private MGDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MGDataProtoDefineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MGDataProtoDefine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string Id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string Addr = 2;</code>
     * @return The addr.
     */
    java.lang.String getAddr();
    /**
     * <code>string Addr = 2;</code>
     * @return The bytes for addr.
     */
    com.google.protobuf.ByteString
        getAddrBytes();

    /**
     * <code>string ChannelId = 3;</code>
     * @return The channelId.
     */
    java.lang.String getChannelId();
    /**
     * <code>string ChannelId = 3;</code>
     * @return The bytes for channelId.
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>string SignalName = 4;</code>
     * @return The signalName.
     */
    java.lang.String getSignalName();
    /**
     * <code>string SignalName = 4;</code>
     * @return The bytes for signalName.
     */
    com.google.protobuf.ByteString
        getSignalNameBytes();

    /**
     * <code>string parameter = 5;</code>
     * @return The parameter.
     */
    java.lang.String getParameter();
    /**
     * <code>string parameter = 5;</code>
     * @return The bytes for parameter.
     */
    com.google.protobuf.ByteString
        getParameterBytes();

    /**
     * <code>.google.protobuf.Any StartTime = 6;</code>
     * @return Whether the startTime field is set.
     */
    boolean hasStartTime();
    /**
     * <code>.google.protobuf.Any StartTime = 6;</code>
     * @return The startTime.
     */
    com.google.protobuf.Any getStartTime();
    /**
     * <code>.google.protobuf.Any StartTime = 6;</code>
     */
    com.google.protobuf.AnyOrBuilder getStartTimeOrBuilder();

    /**
     * <code>.google.protobuf.Any EndTime = 7;</code>
     * @return Whether the endTime field is set.
     */
    boolean hasEndTime();
    /**
     * <code>.google.protobuf.Any EndTime = 7;</code>
     * @return The endTime.
     */
    com.google.protobuf.Any getEndTime();
    /**
     * <code>.google.protobuf.Any EndTime = 7;</code>
     */
    com.google.protobuf.AnyOrBuilder getEndTimeOrBuilder();

    /**
     * <code>.proto.Detail Data = 10;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.proto.Detail Data = 10;</code>
     * @return The data.
     */
    com.learning.compress.proto.MGDataProto.Detail getData();
    /**
     * <code>.proto.Detail Data = 10;</code>
     */
    com.learning.compress.proto.MGDataProto.DetailOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code proto.MGDataProtoDefine}
   */
  public static final class MGDataProtoDefine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MGDataProtoDefine)
      MGDataProtoDefineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MGDataProtoDefine.newBuilder() to construct.
    private MGDataProtoDefine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MGDataProtoDefine() {
      id_ = "";
      addr_ = "";
      channelId_ = "";
      signalName_ = "";
      parameter_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MGDataProtoDefine();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MGDataProtoDefine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              addr_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              signalName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              parameter_ = s;
              break;
            }
            case 50: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (startTime_ != null) {
                subBuilder = startTime_.toBuilder();
              }
              startTime_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startTime_);
                startTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (endTime_ != null) {
                subBuilder = endTime_.toBuilder();
              }
              endTime_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(endTime_);
                endTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              com.learning.compress.proto.MGDataProto.Detail.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.learning.compress.proto.MGDataProto.Detail.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learning.compress.proto.MGDataProto.internal_static_proto_MGDataProtoDefine_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learning.compress.proto.MGDataProto.internal_static_proto_MGDataProtoDefine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learning.compress.proto.MGDataProto.MGDataProtoDefine.class, com.learning.compress.proto.MGDataProto.MGDataProtoDefine.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string Id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string Id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object addr_;
    /**
     * <code>string Addr = 2;</code>
     * @return The addr.
     */
    @java.lang.Override
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      }
    }
    /**
     * <code>string Addr = 2;</code>
     * @return The bytes for addr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELID_FIELD_NUMBER = 3;
    private volatile java.lang.Object channelId_;
    /**
     * <code>string ChannelId = 3;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>string ChannelId = 3;</code>
     * @return The bytes for channelId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNALNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object signalName_;
    /**
     * <code>string SignalName = 4;</code>
     * @return The signalName.
     */
    @java.lang.Override
    public java.lang.String getSignalName() {
      java.lang.Object ref = signalName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signalName_ = s;
        return s;
      }
    }
    /**
     * <code>string SignalName = 4;</code>
     * @return The bytes for signalName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignalNameBytes() {
      java.lang.Object ref = signalName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETER_FIELD_NUMBER = 5;
    private volatile java.lang.Object parameter_;
    /**
     * <code>string parameter = 5;</code>
     * @return The parameter.
     */
    @java.lang.Override
    public java.lang.String getParameter() {
      java.lang.Object ref = parameter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parameter_ = s;
        return s;
      }
    }
    /**
     * <code>string parameter = 5;</code>
     * @return The bytes for parameter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParameterBytes() {
      java.lang.Object ref = parameter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 6;
    private com.google.protobuf.Any startTime_;
    /**
     * <code>.google.protobuf.Any StartTime = 6;</code>
     * @return Whether the startTime field is set.
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return startTime_ != null;
    }
    /**
     * <code>.google.protobuf.Any StartTime = 6;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public com.google.protobuf.Any getStartTime() {
      return startTime_ == null ? com.google.protobuf.Any.getDefaultInstance() : startTime_;
    }
    /**
     * <code>.google.protobuf.Any StartTime = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getStartTimeOrBuilder() {
      return getStartTime();
    }

    public static final int ENDTIME_FIELD_NUMBER = 7;
    private com.google.protobuf.Any endTime_;
    /**
     * <code>.google.protobuf.Any EndTime = 7;</code>
     * @return Whether the endTime field is set.
     */
    @java.lang.Override
    public boolean hasEndTime() {
      return endTime_ != null;
    }
    /**
     * <code>.google.protobuf.Any EndTime = 7;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public com.google.protobuf.Any getEndTime() {
      return endTime_ == null ? com.google.protobuf.Any.getDefaultInstance() : endTime_;
    }
    /**
     * <code>.google.protobuf.Any EndTime = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getEndTimeOrBuilder() {
      return getEndTime();
    }

    public static final int DATA_FIELD_NUMBER = 10;
    private com.learning.compress.proto.MGDataProto.Detail data_;
    /**
     * <code>.proto.Detail Data = 10;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.proto.Detail Data = 10;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.learning.compress.proto.MGDataProto.Detail getData() {
      return data_ == null ? com.learning.compress.proto.MGDataProto.Detail.getDefaultInstance() : data_;
    }
    /**
     * <code>.proto.Detail Data = 10;</code>
     */
    @java.lang.Override
    public com.learning.compress.proto.MGDataProto.DetailOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addr_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, channelId_);
      }
      if (!getSignalNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signalName_);
      }
      if (!getParameterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parameter_);
      }
      if (startTime_ != null) {
        output.writeMessage(6, getStartTime());
      }
      if (endTime_ != null) {
        output.writeMessage(7, getEndTime());
      }
      if (data_ != null) {
        output.writeMessage(10, getData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addr_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, channelId_);
      }
      if (!getSignalNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signalName_);
      }
      if (!getParameterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parameter_);
      }
      if (startTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getStartTime());
      }
      if (endTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getEndTime());
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learning.compress.proto.MGDataProto.MGDataProtoDefine)) {
        return super.equals(obj);
      }
      com.learning.compress.proto.MGDataProto.MGDataProtoDefine other = (com.learning.compress.proto.MGDataProto.MGDataProtoDefine) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getAddr()
          .equals(other.getAddr())) return false;
      if (!getChannelId()
          .equals(other.getChannelId())) return false;
      if (!getSignalName()
          .equals(other.getSignalName())) return false;
      if (!getParameter()
          .equals(other.getParameter())) return false;
      if (hasStartTime() != other.hasStartTime()) return false;
      if (hasStartTime()) {
        if (!getStartTime()
            .equals(other.getStartTime())) return false;
      }
      if (hasEndTime() != other.hasEndTime()) return false;
      if (hasEndTime()) {
        if (!getEndTime()
            .equals(other.getEndTime())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      hash = (37 * hash) + SIGNALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSignalName().hashCode();
      hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getParameter().hashCode();
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learning.compress.proto.MGDataProto.MGDataProtoDefine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MGDataProtoDefine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MGDataProtoDefine)
        com.learning.compress.proto.MGDataProto.MGDataProtoDefineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learning.compress.proto.MGDataProto.internal_static_proto_MGDataProtoDefine_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learning.compress.proto.MGDataProto.internal_static_proto_MGDataProtoDefine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learning.compress.proto.MGDataProto.MGDataProtoDefine.class, com.learning.compress.proto.MGDataProto.MGDataProtoDefine.Builder.class);
      }

      // Construct using com.learning.compress.proto.MGDataProto.MGDataProtoDefine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        addr_ = "";

        channelId_ = "";

        signalName_ = "";

        parameter_ = "";

        if (startTimeBuilder_ == null) {
          startTime_ = null;
        } else {
          startTime_ = null;
          startTimeBuilder_ = null;
        }
        if (endTimeBuilder_ == null) {
          endTime_ = null;
        } else {
          endTime_ = null;
          endTimeBuilder_ = null;
        }
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learning.compress.proto.MGDataProto.internal_static_proto_MGDataProtoDefine_descriptor;
      }

      @java.lang.Override
      public com.learning.compress.proto.MGDataProto.MGDataProtoDefine getDefaultInstanceForType() {
        return com.learning.compress.proto.MGDataProto.MGDataProtoDefine.getDefaultInstance();
      }

      @java.lang.Override
      public com.learning.compress.proto.MGDataProto.MGDataProtoDefine build() {
        com.learning.compress.proto.MGDataProto.MGDataProtoDefine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learning.compress.proto.MGDataProto.MGDataProtoDefine buildPartial() {
        com.learning.compress.proto.MGDataProto.MGDataProtoDefine result = new com.learning.compress.proto.MGDataProto.MGDataProtoDefine(this);
        result.id_ = id_;
        result.addr_ = addr_;
        result.channelId_ = channelId_;
        result.signalName_ = signalName_;
        result.parameter_ = parameter_;
        if (startTimeBuilder_ == null) {
          result.startTime_ = startTime_;
        } else {
          result.startTime_ = startTimeBuilder_.build();
        }
        if (endTimeBuilder_ == null) {
          result.endTime_ = endTime_;
        } else {
          result.endTime_ = endTimeBuilder_.build();
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learning.compress.proto.MGDataProto.MGDataProtoDefine) {
          return mergeFrom((com.learning.compress.proto.MGDataProto.MGDataProtoDefine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learning.compress.proto.MGDataProto.MGDataProtoDefine other) {
        if (other == com.learning.compress.proto.MGDataProto.MGDataProtoDefine.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getAddr().isEmpty()) {
          addr_ = other.addr_;
          onChanged();
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (!other.getSignalName().isEmpty()) {
          signalName_ = other.signalName_;
          onChanged();
        }
        if (!other.getParameter().isEmpty()) {
          parameter_ = other.parameter_;
          onChanged();
        }
        if (other.hasStartTime()) {
          mergeStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          mergeEndTime(other.getEndTime());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learning.compress.proto.MGDataProto.MGDataProtoDefine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learning.compress.proto.MGDataProto.MGDataProtoDefine) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string Id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string Id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object addr_ = "";
      /**
       * <code>string Addr = 2;</code>
       * @return The addr.
       */
      public java.lang.String getAddr() {
        java.lang.Object ref = addr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Addr = 2;</code>
       * @return The bytes for addr.
       */
      public com.google.protobuf.ByteString
          getAddrBytes() {
        java.lang.Object ref = addr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Addr = 2;</code>
       * @param value The addr to set.
       * @return This builder for chaining.
       */
      public Builder setAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Addr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddr() {
        
        addr_ = getDefaultInstance().getAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string Addr = 2;</code>
       * @param value The bytes for addr to set.
       * @return This builder for chaining.
       */
      public Builder setAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>string ChannelId = 3;</code>
       * @return The channelId.
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ChannelId = 3;</code>
       * @return The bytes for channelId.
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ChannelId = 3;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ChannelId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>string ChannelId = 3;</code>
       * @param value The bytes for channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signalName_ = "";
      /**
       * <code>string SignalName = 4;</code>
       * @return The signalName.
       */
      public java.lang.String getSignalName() {
        java.lang.Object ref = signalName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signalName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string SignalName = 4;</code>
       * @return The bytes for signalName.
       */
      public com.google.protobuf.ByteString
          getSignalNameBytes() {
        java.lang.Object ref = signalName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signalName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string SignalName = 4;</code>
       * @param value The signalName to set.
       * @return This builder for chaining.
       */
      public Builder setSignalName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signalName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string SignalName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignalName() {
        
        signalName_ = getDefaultInstance().getSignalName();
        onChanged();
        return this;
      }
      /**
       * <code>string SignalName = 4;</code>
       * @param value The bytes for signalName to set.
       * @return This builder for chaining.
       */
      public Builder setSignalNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signalName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parameter_ = "";
      /**
       * <code>string parameter = 5;</code>
       * @return The parameter.
       */
      public java.lang.String getParameter() {
        java.lang.Object ref = parameter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parameter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string parameter = 5;</code>
       * @return The bytes for parameter.
       */
      public com.google.protobuf.ByteString
          getParameterBytes() {
        java.lang.Object ref = parameter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parameter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string parameter = 5;</code>
       * @param value The parameter to set.
       * @return This builder for chaining.
       */
      public Builder setParameter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string parameter = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameter() {
        
        parameter_ = getDefaultInstance().getParameter();
        onChanged();
        return this;
      }
      /**
       * <code>string parameter = 5;</code>
       * @param value The bytes for parameter to set.
       * @return This builder for chaining.
       */
      public Builder setParameterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parameter_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any startTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> startTimeBuilder_;
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       * @return Whether the startTime field is set.
       */
      public boolean hasStartTime() {
        return startTimeBuilder_ != null || startTime_ != null;
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       * @return The startTime.
       */
      public com.google.protobuf.Any getStartTime() {
        if (startTimeBuilder_ == null) {
          return startTime_ == null ? com.google.protobuf.Any.getDefaultInstance() : startTime_;
        } else {
          return startTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      public Builder setStartTime(com.google.protobuf.Any value) {
        if (startTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startTime_ = value;
          onChanged();
        } else {
          startTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      public Builder setStartTime(
          com.google.protobuf.Any.Builder builderForValue) {
        if (startTimeBuilder_ == null) {
          startTime_ = builderForValue.build();
          onChanged();
        } else {
          startTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      public Builder mergeStartTime(com.google.protobuf.Any value) {
        if (startTimeBuilder_ == null) {
          if (startTime_ != null) {
            startTime_ =
              com.google.protobuf.Any.newBuilder(startTime_).mergeFrom(value).buildPartial();
          } else {
            startTime_ = value;
          }
          onChanged();
        } else {
          startTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      public Builder clearStartTime() {
        if (startTimeBuilder_ == null) {
          startTime_ = null;
          onChanged();
        } else {
          startTime_ = null;
          startTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      public com.google.protobuf.Any.Builder getStartTimeBuilder() {
        
        onChanged();
        return getStartTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      public com.google.protobuf.AnyOrBuilder getStartTimeOrBuilder() {
        if (startTimeBuilder_ != null) {
          return startTimeBuilder_.getMessageOrBuilder();
        } else {
          return startTime_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : startTime_;
        }
      }
      /**
       * <code>.google.protobuf.Any StartTime = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getStartTimeFieldBuilder() {
        if (startTimeBuilder_ == null) {
          startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getStartTime(),
                  getParentForChildren(),
                  isClean());
          startTime_ = null;
        }
        return startTimeBuilder_;
      }

      private com.google.protobuf.Any endTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> endTimeBuilder_;
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       * @return Whether the endTime field is set.
       */
      public boolean hasEndTime() {
        return endTimeBuilder_ != null || endTime_ != null;
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       * @return The endTime.
       */
      public com.google.protobuf.Any getEndTime() {
        if (endTimeBuilder_ == null) {
          return endTime_ == null ? com.google.protobuf.Any.getDefaultInstance() : endTime_;
        } else {
          return endTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      public Builder setEndTime(com.google.protobuf.Any value) {
        if (endTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endTime_ = value;
          onChanged();
        } else {
          endTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      public Builder setEndTime(
          com.google.protobuf.Any.Builder builderForValue) {
        if (endTimeBuilder_ == null) {
          endTime_ = builderForValue.build();
          onChanged();
        } else {
          endTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      public Builder mergeEndTime(com.google.protobuf.Any value) {
        if (endTimeBuilder_ == null) {
          if (endTime_ != null) {
            endTime_ =
              com.google.protobuf.Any.newBuilder(endTime_).mergeFrom(value).buildPartial();
          } else {
            endTime_ = value;
          }
          onChanged();
        } else {
          endTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      public Builder clearEndTime() {
        if (endTimeBuilder_ == null) {
          endTime_ = null;
          onChanged();
        } else {
          endTime_ = null;
          endTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      public com.google.protobuf.Any.Builder getEndTimeBuilder() {
        
        onChanged();
        return getEndTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      public com.google.protobuf.AnyOrBuilder getEndTimeOrBuilder() {
        if (endTimeBuilder_ != null) {
          return endTimeBuilder_.getMessageOrBuilder();
        } else {
          return endTime_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : endTime_;
        }
      }
      /**
       * <code>.google.protobuf.Any EndTime = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getEndTimeFieldBuilder() {
        if (endTimeBuilder_ == null) {
          endTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getEndTime(),
                  getParentForChildren(),
                  isClean());
          endTime_ = null;
        }
        return endTimeBuilder_;
      }

      private com.learning.compress.proto.MGDataProto.Detail data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.learning.compress.proto.MGDataProto.Detail, com.learning.compress.proto.MGDataProto.Detail.Builder, com.learning.compress.proto.MGDataProto.DetailOrBuilder> dataBuilder_;
      /**
       * <code>.proto.Detail Data = 10;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       * @return The data.
       */
      public com.learning.compress.proto.MGDataProto.Detail getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.learning.compress.proto.MGDataProto.Detail.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      public Builder setData(com.learning.compress.proto.MGDataProto.Detail value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      public Builder setData(
          com.learning.compress.proto.MGDataProto.Detail.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      public Builder mergeData(com.learning.compress.proto.MGDataProto.Detail value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.learning.compress.proto.MGDataProto.Detail.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      public com.learning.compress.proto.MGDataProto.Detail.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      public com.learning.compress.proto.MGDataProto.DetailOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.learning.compress.proto.MGDataProto.Detail.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.proto.Detail Data = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.learning.compress.proto.MGDataProto.Detail, com.learning.compress.proto.MGDataProto.Detail.Builder, com.learning.compress.proto.MGDataProto.DetailOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.learning.compress.proto.MGDataProto.Detail, com.learning.compress.proto.MGDataProto.Detail.Builder, com.learning.compress.proto.MGDataProto.DetailOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MGDataProtoDefine)
    }

    // @@protoc_insertion_point(class_scope:proto.MGDataProtoDefine)
    private static final com.learning.compress.proto.MGDataProto.MGDataProtoDefine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learning.compress.proto.MGDataProto.MGDataProtoDefine();
    }

    public static com.learning.compress.proto.MGDataProto.MGDataProtoDefine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MGDataProtoDefine>
        PARSER = new com.google.protobuf.AbstractParser<MGDataProtoDefine>() {
      @java.lang.Override
      public MGDataProtoDefine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MGDataProtoDefine(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MGDataProtoDefine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MGDataProtoDefine> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learning.compress.proto.MGDataProto.MGDataProtoDefine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Detail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 time = 1;</code>
     * @return A list containing the time.
     */
    java.util.List<java.lang.Integer> getTimeList();
    /**
     * <code>repeated int32 time = 1;</code>
     * @return The count of time.
     */
    int getTimeCount();
    /**
     * <code>repeated int32 time = 1;</code>
     * @param index The index of the element to return.
     * @return The time at the given index.
     */
    int getTime(int index);

    /**
     * <code>repeated float data = 2;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.Float> getDataList();
    /**
     * <code>repeated float data = 2;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated float data = 2;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    float getData(int index);
  }
  /**
   * Protobuf type {@code proto.Detail}
   */
  public static final class Detail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Detail)
      DetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Detail.newBuilder() to construct.
    private Detail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Detail() {
      time_ = emptyIntList();
      data_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Detail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Detail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                time_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              time_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                time_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                time_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                data_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.addFloat(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                data_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          time_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          data_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learning.compress.proto.MGDataProto.internal_static_proto_Detail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learning.compress.proto.MGDataProto.internal_static_proto_Detail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learning.compress.proto.MGDataProto.Detail.class, com.learning.compress.proto.MGDataProto.Detail.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList time_;
    /**
     * <code>repeated int32 time = 1;</code>
     * @return A list containing the time.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getTimeList() {
      return time_;
    }
    /**
     * <code>repeated int32 time = 1;</code>
     * @return The count of time.
     */
    public int getTimeCount() {
      return time_.size();
    }
    /**
     * <code>repeated int32 time = 1;</code>
     * @param index The index of the element to return.
     * @return The time at the given index.
     */
    public int getTime(int index) {
      return time_.getInt(index);
    }
    private int timeMemoizedSerializedSize = -1;

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.FloatList data_;
    /**
     * <code>repeated float data = 2;</code>
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated float data = 2;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated float data = 2;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public float getData(int index) {
      return data_.getFloat(index);
    }
    private int dataMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getTimeList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(timeMemoizedSerializedSize);
      }
      for (int i = 0; i < time_.size(); i++) {
        output.writeInt32NoTag(time_.getInt(i));
      }
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeFloatNoTag(data_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < time_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(time_.getInt(i));
        }
        size += dataSize;
        if (!getTimeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        timeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getDataList().size();
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learning.compress.proto.MGDataProto.Detail)) {
        return super.equals(obj);
      }
      com.learning.compress.proto.MGDataProto.Detail other = (com.learning.compress.proto.MGDataProto.Detail) obj;

      if (!getTimeList()
          .equals(other.getTimeList())) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTimeCount() > 0) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTimeList().hashCode();
      }
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learning.compress.proto.MGDataProto.Detail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learning.compress.proto.MGDataProto.Detail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Detail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Detail)
        com.learning.compress.proto.MGDataProto.DetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learning.compress.proto.MGDataProto.internal_static_proto_Detail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learning.compress.proto.MGDataProto.internal_static_proto_Detail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learning.compress.proto.MGDataProto.Detail.class, com.learning.compress.proto.MGDataProto.Detail.Builder.class);
      }

      // Construct using com.learning.compress.proto.MGDataProto.Detail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learning.compress.proto.MGDataProto.internal_static_proto_Detail_descriptor;
      }

      @java.lang.Override
      public com.learning.compress.proto.MGDataProto.Detail getDefaultInstanceForType() {
        return com.learning.compress.proto.MGDataProto.Detail.getDefaultInstance();
      }

      @java.lang.Override
      public com.learning.compress.proto.MGDataProto.Detail build() {
        com.learning.compress.proto.MGDataProto.Detail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learning.compress.proto.MGDataProto.Detail buildPartial() {
        com.learning.compress.proto.MGDataProto.Detail result = new com.learning.compress.proto.MGDataProto.Detail(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          time_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000002) != 0)) {
          data_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learning.compress.proto.MGDataProto.Detail) {
          return mergeFrom((com.learning.compress.proto.MGDataProto.Detail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learning.compress.proto.MGDataProto.Detail other) {
        if (other == com.learning.compress.proto.MGDataProto.Detail.getDefaultInstance()) return this;
        if (!other.time_.isEmpty()) {
          if (time_.isEmpty()) {
            time_ = other.time_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTimeIsMutable();
            time_.addAll(other.time_);
          }
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learning.compress.proto.MGDataProto.Detail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learning.compress.proto.MGDataProto.Detail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList time_ = emptyIntList();
      private void ensureTimeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          time_ = mutableCopy(time_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @return A list containing the time.
       */
      public java.util.List<java.lang.Integer>
          getTimeList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(time_) : time_;
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @return The count of time.
       */
      public int getTimeCount() {
        return time_.size();
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @param index The index of the element to return.
       * @return The time at the given index.
       */
      public int getTime(int index) {
        return time_.getInt(index);
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @param index The index to set the value at.
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          int index, int value) {
        ensureTimeIsMutable();
        time_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @param value The time to add.
       * @return This builder for chaining.
       */
      public Builder addTime(int value) {
        ensureTimeIsMutable();
        time_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @param values The time to add.
       * @return This builder for chaining.
       */
      public Builder addAllTime(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTimeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, time_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        time_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList data_ = emptyFloatList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          data_ = mutableCopy(data_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float data = 2;</code>
       * @return A list containing the data.
       */
      public java.util.List<java.lang.Float>
          getDataList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <code>repeated float data = 2;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated float data = 2;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public float getData(int index) {
        return data_.getFloat(index);
      }
      /**
       * <code>repeated float data = 2;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, float value) {
        ensureDataIsMutable();
        data_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 2;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(float value) {
        ensureDataIsMutable();
        data_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 2;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Detail)
    }

    // @@protoc_insertion_point(class_scope:proto.Detail)
    private static final com.learning.compress.proto.MGDataProto.Detail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learning.compress.proto.MGDataProto.Detail();
    }

    public static com.learning.compress.proto.MGDataProto.Detail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Detail>
        PARSER = new com.google.protobuf.AbstractParser<Detail>() {
      @java.lang.Override
      public Detail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Detail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Detail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Detail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learning.compress.proto.MGDataProto.Detail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MGDataProtoDefine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MGDataProtoDefine_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Detail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Detail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MGData.proto\022\005proto\032\031google/protobuf/a" +
      "ny.proto\"\324\001\n\021MGDataProtoDefine\022\n\n\002Id\030\001 \001" +
      "(\t\022\014\n\004Addr\030\002 \001(\t\022\021\n\tChannelId\030\003 \001(\t\022\022\n\nS" +
      "ignalName\030\004 \001(\t\022\021\n\tparameter\030\005 \001(\t\022\'\n\tSt" +
      "artTime\030\006 \001(\0132\024.google.protobuf.Any\022%\n\007E" +
      "ndTime\030\007 \001(\0132\024.google.protobuf.Any\022\033\n\004Da" +
      "ta\030\n \001(\0132\r.proto.Detail\"$\n\006Detail\022\014\n\004tim" +
      "e\030\001 \003(\005\022\014\n\004data\030\002 \003(\002B*\n\033com.learning.co" +
      "mpress.protoB\013MGDataProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_proto_MGDataProtoDefine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MGDataProtoDefine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MGDataProtoDefine_descriptor,
        new java.lang.String[] { "Id", "Addr", "ChannelId", "SignalName", "Parameter", "StartTime", "EndTime", "Data", });
    internal_static_proto_Detail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Detail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Detail_descriptor,
        new java.lang.String[] { "Time", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
